# This file is used by travis-ci.org to test META-SHARE
# env section
# ============
# This section sets environment variables. There are two kinds of environment
# variables in travis: "global" and "matrix".
# 
# matrix variables
# -----------------
# matrix variables can be used to tell travis we want different jobs to run
# for instance to split the testsuite in two subgroups.
# Here TEST_SUITE takes two different values, so in one case the selenium
# tests run, and in the other case the rest of the tests run.
#
# global variables
# -----------------
# Common environment variables for all the jobs that will run.
#
# In order to securely use external services (such as coveralls or sauce labs) 
# with travis and github some secrets have to be shared. Travis provides
# an option to encrypt environment variables in a way that only travis can
# decrypt them and use them with the external services. By doing that, we can
# safely store encrypted keys in this file and let travis decrypt and use them.
#
language: python
env:
  global:
    ######## SAUCE LABS #############
    # SAUCE_USERNAME and SAUCE_ACCESS_KEY
    # https://docs.saucelabs.com/ci-integrations/travis-ci/
    # You will need to create a saucelabs account, free for Free Software projects.
    # ### keys for zeehio/META-SHARE:
    - secure: IEtbjPMMqI9qiL9JzCoqkN4t700OOG6lM83a0M9PgIpuFviC7cmUv984Vpk55yuvnIvFp5N+BzIWFbw4frxV8Al+usVZs/WHdvwMKZfoolKY4uQAeibnQzivh5DJqRjz3A8nplH953SBosseVqXW6xQBKmexNdUmA7Iz6Tjag0A=
    - secure: gi7/2rLtpYgaj4tld5eB1dL9jrRXfGAxeOVtBMAura+qKKknNE0iY0lJc6OSwY7imTRQUyg2A4xWFD0lSEw6ZQ2JpZzbCFXYXD5wsm5PPNw5lCWSUKLd1E4in9wmmQ6/tjlqH7J3DWD16Pb2AyE9RVN2jWMGUif73qygSneDudU=
    #
    # ### keys for jsteffen/META-SHARE:
    - secure: FG2VtZKmd22Ji1FJCvGmUxq7XyVE5YxP1PYfvDeJ1Z4G3Liv2HkMUGKNjM7mHs5xHLjQERT0c9UnaemuXaEX1GgnKkD/z8xlWMFCcca0wM7jrH65pS6uzBVIRLtyGUOH0NV7tyD8lIdBopZPidOCS4sacdjEkw7V8zvJbS5v15msBp1gqE+mp+MAHEmGN7euOywvBvUMbEvu8yosj1+dL83+QcpxecInK5VvnwaYvpSgnakQB0PeH7E/+epYWiPKit6WtmA1VhBUYfBuCoV6aWy4YTto20Rhece+gXS/wxdDJuh7BlsbWpcsRu8I5P/GqcwM7qJSuwCIRD7W2BeIZR7HTrtiDWtJ+aPjUxpVVhonkvmoC9EvewBNCks592GKTyrFKLkE74AsBArz9LY7u36uyTlF0zP2SsN6hmIzTYrrDSAXiw4dPWfdgJbXeAJWG+NJnUkRyr4kD0vNwSwD+orG+lqXjiCuFKb5RWxXf4FAiuIysFNIx1Cy0gKUmxnd11D8GPzpqPEygmE1F2Q9VLGQJ7q+R6p+uz9ApW0sbjU9OFyPB8mHGUhVq/UTUxLDME6Kfi0MtRyXwhbrdMtTK9+92P4KCjrlheBo49hLvW2Y8/pRhVHQm1LSXmtZB5aXD9M14HK0FTn4iTVy0JOoBgSdqNtA6cSnbp1aOd4sA8o=
    - secure: ZhxlxxGnr41ZidU0EsimsLiXcQR5Z8JdIJCEoTmNJ6sw8117jyycGHQDQzmrrPaR53glXbQXIhryHdcJ7gvx0DCiceAdmTygzVpzLcKpU2gNM/vMl9R1XsAxFHsc528IFtakV08dX05iCAtrtf1I3LroLyrtgVbf1u8+zz8ZCe5JV8dfRZmWRTdS3O6sA/FV8kcoLOVVMQLhqA0C4dd31VoPmO6zHEBjJwzbrR9rysf65NOcykfcgTzfCpvEOs3zNo4lv85mRdbjoJC5HQBw/Zh40laimTC45N9hppwhGGcMMnSPVtPj7ubvCeWheNYk3KuQNBMQYy3+q/ThdyE2kYZTjCpwy0vTYibctjO5bJFbNXsQilIQMVwVt24+eJqu61gosnWlGj90UJ1phOFQYSb8esL89M23xKTk/s7rxZfGsd7HXq1bibijnEVAUxWKBEfi9eac9+Pjx75WMYz+B6Vf7WNgWV76moy02fuFh+bGyLyKp23REa8TqdgwH0Jaj41stoC0TOGUF8mBzsPTAILrYX2MJuA0Jz1QeI6UUYgEaxd0oQcVQHYjJ0ZO8Yg61/GXHM5Vnlxsu0Ur2ZYswUP1bEoVMXZ8CzO99oaYphvn58mPdmfZS0H7xkkEs6Dma397fgKA5+oyE5Uncodn3CbNXSbXjrHX1xoSKzFY3lM=
    #
    # ### keys for metashare/META-SHARE:
    # - secure: key_not_yet_created
    # - secure: key_not_yet_created
    #
    ########### GIVE TRAVIS PUSH ACCESS ##########
    # So we can push the generated gh-pages
    # Generate your auth token here:
    # https://github.com/settings/applications#personal-access-tokens
    # Encrypt your token:
    # $ gem install travis;
    # $ travis login
    # $ travis encrypt -r zeehio/META-SHARE "GH_AUTH='my_secret_token'"
    # $ travis encrypt -r zeehio/META-SHARE "GH_REF=github.com/zeehio/META-SHARE.git"
    # The repository GH_REF is not secret, but if we encrypt it we can keep 
    # the zeehio/META-SHARE and the metashare/META-SHARE and travis will choose the
    # right one on each case.
    #
    # ### keys for zeehio/META-SHARE:
    # GH_AUTH:
    - secure: "DmTgKEmMQatjTflWlDpX0PXJf/Gh8kiBqv09AkgjdO+5imCLJ0QcQbusZ2VeJPXVyvPQ/rywSCW1KJQrcZz/nJEX1kClWsV4z157oQAAroIsaAlHi77pPEQGg6EU6CXNHJp1U2v+sgeMx73KjYgHgVXPtOB7LqF6V0CWeQER+UA="
    # GH_REF:
    - secure: "k3+QkIQtF5chdMOBVWbuhVIVJ6KMWQ2FgyekBSbknAz7y8CmxtTuFw4Wgitja/3ESgbdsRY9z7/vMtMaxk5aNJWq8lZodMzhil0f0k+cKKbl+vMViBAomXKcCCCMpUACBObhJXuK5T4f0LhbqYdmXtOF5cubn5gDr33MV5Dk0+Q="
    # ### keys for jsteffen/META-SHARE:
    # GH_AUTH:
    - secure: "oK01Q6xxJgGL1csGRrUP9UiORx1SXOyy+S/C1YmYPaCI7ANWewhXF82ZX7HT/FOawNUGEAllQsABRo7Iea11xaSP+5UZ/lEVT/XJp6Z5AHvmYQgqTh8VfZwxxAtrphjkCoiAZMDWZ724mvtmIfQuZkFkJgBUyd1qHgPH9BfjpUcuOQYdIjOsFovtNpIkACN2o1/2sl2ad/6SZRlTsQtP77nNfNRTdKHSW0CmqEOkWO+rzFvXU0IndLImKwfD1fYoy2s0/S+XUFW2k/qZCnPC1/5ATjZjHYUkzJxWf1hP7EegWIGoU4PbM88h3RsHdAd8A20sJRvED1YCQ+TmD7W6jstL6M3H1/u4VPqhf45zFMadE6ny3ejUxKOR4vyoxXF044V+CzVtzv/CkGFIDVFECIuo9/tDFcBjrV75f8r9c1qni4Hky/Fca5AWdhMh4InbcvGFWIvXmkT4gm5BqS+uzqoK67U6ZTIeXhoZ5+4N4MhqfQ/m8eFcnEmuxguBXljTpBxaqYlF+HZIQ3H6ty0KHDiLFfRnoJcQNpSY5lIVPDUulPSD5ZyHCjFWhCPmAldrqIvF/7+/YEVcSf7dA+Ken7pMGGbKt7iOrPV9+v3EvEYZtB1XM1h9lkNq51mEso2I3tMYxWtAOIOYzdcG2EdqoA3cN7amQozxixDLvJpZFLw="
    # GH_REF:
    - secure: "VB8yedjjISBVpwzNN4yvC4P/9DS389uX8VWCkeyIbsyf4WMfqxXMqv8AXrleYrodI8HrxvPwtZoc5V30xnvb8V5q9R+Ibu2xW7yT53cnEpzJjR/CG2+vBA9DfPFXH70wWbWtcT1cyiwz85BBxFwTX66m3QKreWYk1Ei2qD3/kjavaiRI7nPmoc6JTYwHhvUOUMZ08wq/z8M28VPFDS1FlQxPAN6Kl5ZCD3NR5QFy+cMJ8DKdKngCq5hZjnJ+KJNXNUgY0ZLQGMIegNWEhmQ/zTu+vu7VyMTGKHkE1D+0BHmVgoF23O4oMDcyUDTXuNn8JnI1DIs3rXarTRNyUkMgyGc1PPzZM7H4zUA1liHFaqrmiq1YV5m4OFPw6KwT/oAXrJ7zInBD+36xvT4ZlsnwNUGge3ZrgTDVfC+fiOB14UHnntenS7ygNefNYbROHSGTmj16wgp1CXjuyAj5A3wEPaT/isM4HV4kW1QS03sp1zYRkIR4R2M6sMO9ODU7XDvzL83Ovsb6EdKX2fJTRM6rdc2vDJ3DaPWaQDB6B/S2aRhU/E/mskTr8y/HYyxQCtvfXTnX3fEkVGI7Tx3bkDas8NBmTEuJ+7Uq6yqn9osrR/e6iyZ+9p9dv9ndVMKCXEPNJdjEfGryhZpyWATfNHC3t0dlfH7Kdm1xv+vpzqMoxRo="
    # ### keys for metashare/META-SHARE:
    #- secure: "not generated"
    # GH_REF:
    #- secure: "not generated"
  matrix:
    # basic runs the metashare testsuite without selenium tests, followed
    # by the multitest that checks node syncing.
    # selenium runs the selenium tests only
    # docs builds the documentation and pushes it to gh-pages
    - TEST_SUITE="basic"
    - TEST_SUITE="selenium"
    - TEST_SUITE="docs"
python:
  - "2.7"
# commands to install dependencies
install:
  - "pip install coveralls"
  - "./install-dependencies.sh"
# command to run tests
script:
  - "if [ \"x$TEST_SUITE\" = \"xbasic\" ]; then ./misc/test-ci/run-testsuite.sh; fi"
  - "if [ \"x$TEST_SUITE\" = \"xselenium\" ]; then ./misc/test-ci/run-testsuite.sh --selenium-only; fi"
  - "if [ \"x$TEST_SUITE\" = \"xdocs\" ] ; then ./misc/test-ci/autoupdate-docs.sh; fi"
  - "if [ \"x$TEST_SUITE\" = \"xbasic\" ] ; then ./misc/test-ci/multitest.sh; fi"
after_success:
  - "if [ \"x$TEST_SUITE\" != \"xdocs\" ]; then coveralls; fi"

addons:
  sauce_connect: true
  apt:
    packages:
    - libpq-dev
    - python-sphinx

sudo: false

