---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: solr
  name: solr
spec:
  replicas: 1
  selector:
    app: solr
    deploymentconfig: solr
  template:
    metadata:
      labels:
        app: solr
        deploymentconfig: solr
    spec:
      containers:
      # - image: "docker-registry.default.svc:5000/jkataja-training/solr-metashare:latest"
      - image: solr-metashare:latest
        name: solr
        ports:
        - containerPort: 8983
          protocol: TCP
      resources: {}
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - solr
      from:
        name: solr-metashare:latest

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: solr
  name: solr
spec:
  ports:
  - name: 8983-tcp
    port: 8983
    protocol: TCP
    targetPort: 8983
  selector:
    app: solr
    deploymentconfig: solr
